---
title: "Final Project Milestone 1: Proposal"
author: Cameron Reaves
output: pdf_document
---


## Proposal
Does the politcal affiliation of the presidential administration affect the rate of success of environmental judicial decisions in the US District courts, controlling for political appointment of judges. 
The null hypothesis is that there is no effect. My alternative hypothesis is that the presidential administration does affect the success rate of environmental judicial decisions.
I have found a dataset of US District Court cases that date from the early 20th century to 2012. A subset of these cases are coded as relating to the environment. Of these cases, a success is a positive decision for environmental issues, a negative the converse. This variable is binary and coded as a 1 or 0. This dataset also has the affiliation of the judge presiding over the case. The politcal administation is common knowledge and will mapped to the court decisions. 
I am looking for a statistical change between how judges rule that goes against long term trends. For example, if there is a long-term trend where more environemtal cases are won, I want to see some difference in this change between administrations. An observed pattern that would disprove my hypothesis would be that there is no statistically significant difference in the data. 

Datasets:

https://www.umassd.edu/cas/polisci/resources/us-district-court-database/

https://github.com/taitcha/American_cabinet_appointments

https://www.kaggle.com/harshitagpt/us-presidents